---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "webhooks.fullname" . }}-nginx-config
  labels:
    {{- include "webhooks.labels" . | nindent 4 }}
data:
  index.php: ''
  default.conf: |
    server {
        listen {{ .Values.nginx.port }};

        root /var/www/html/public;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index.php(/|$) {
            fastcgi_pass localhost:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param HTTP_X_REQUEST_ID $request_uid;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            internal;
        }

        location ~ \.php$ {
            return 404;
        }

        location /healthz {
            access_log off;
            try_files $uri /index.php$is_args$args;
        }

        location /status {
            access_log off;
            stub_status on;
        }
    }
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        server_tokens off;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;

        keepalive_requests 100;
        keepalive_timeout 65;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        map $http_x_request_id $request_uid {
            default   $http_x_request_id;
            ""        $request_id;
        }

        log_format docker '$remote_addr - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $request_time $request_uid';

        access_log /var/log/nginx/access.log docker;
        error_log /var/log/nginx/error.log error;

        include /etc/nginx/conf.d/*.conf;
    }
