{{- range tuple "" "dependencies" }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  {{- if eq . "dependencies" }}
  name: {{ template "webhooks.fullname" $ }}-php-config-dependencies
  labels:
    {{- include "webhooks.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- else }}
  name: {{ template "webhooks.fullname" $ }}-php-config
  labels:
    {{- include "webhooks.labels" $ | nindent 4 }}
  {{- end }}
data:
  TIMEZONE: {{ $.Values.php.config.timezone | b64enc | squote }}
  DATABASE_URL: {{ printf "mysql://%s:%s@%s:%s/%s?serverVersion=%s&charset=%s" $.Values.dependencies.mysql.rootUser $.Values.dependencies.mysql.rootPassword $.Values.dependencies.mysql.host ($.Values.dependencies.mysql.port | toString) $.Values.dependencies.mysql.database $.Values.dependencies.mysql.version $.Values.dependencies.mysql.charset | b64enc | squote }}
  MESSENGER_TRANSPORT_DSN: {{ printf "amqp://%s:%s@%s:%s/%s?auto_setup=true" $.Values.dependencies.amqp.user $.Values.dependencies.amqp.password $.Values.dependencies.amqp.host ($.Values.dependencies.amqp.port | toString) ($.Values.dependencies.amqp.vhost | urlquery) | b64enc | squote }}
  MESSENGER_YAVIN_TRANSPORT_DSN: {{ printf "amqp://%s:%s@%s:%s/%s?auto_setup=false" $.Values.dependencies.amqp_yavin.user $.Values.dependencies.amqp_yavin.password $.Values.dependencies.amqp_yavin.host ($.Values.dependencies.amqp_yavin.port | toString) ($.Values.dependencies.amqp_yavin.vhost | urlquery) | b64enc | squote }}
{{- end }}
