---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "webhooks.fullname" . }}
  labels:
    {{- include "webhooks.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    chart: {{ template "webhooks.chart" . }}
    name: web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
